#!/bin/bash

# iOS and OSX Icon
sips -Z 512 icon.png --out mac/icon512.png

sips -Z 120 icon.png --out mac/Icon-60@2x.png
sips -Z 120 icon.png --out mac/Icon-60@2x-1.png
sips -Z 120 icon.png --out mac/Icon-60@2x-2.png
sips -Z 180 icon.png --out mac/Icon-60@3x.png
sips -Z 180 icon.png --out mac/Icon-60@3x-1.png
sips -Z 180 icon.png --out mac/Icon-60@3x-2.png

sips -Z 152 icon.png --out mac/Icon-76@2x.png
sips -Z 152 icon.png --out mac/Icon-76@2x-1.png
sips -Z 152 icon.png --out mac/Icon-76@2x-2.png

sips -Z 76 icon.png --out mac/Icon-76.png
sips -Z 76 icon.png --out mac/Icon-77.png
sips -Z 76 icon.png --out mac/Icon-78.png

# Android Icon
sips -Z 128 icon.png --out mac/Icon-128.png
